name: myenv  # You can change this to your preferred environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Use the required version
  - pip
  - setuptools
  - flake8  # Added flake8 directly to the environment
  - zlib
  - xz
  - tk
  - sqlite
  - readline
  - openssl
  - ncurses
  - libffi
  - libedit
  - certifi
  - ca-certificates
