name: myenv  # You can replace 'myenv' with your desired environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # You can specify the Python version you need
  - pip
  - setuptools
  - zlib
  - xz
  - tk
  - sqlite
  - readline
  - openssl
  - ncurses
  - libffi
  - libedit
  - certifi
  - ca-certificates
