name: myenv  # Your environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Use the required version
  - pip
  - setuptools
  - flake8  # Ensure flake8 is included
  - zlib
  - xz
  - tk
  - sqlite
  - readline
  - openssl
  - ncurses
  - libffi
  - libedit
  - certifi
  - ca-certificates
